### ISSUE TITLE
Android Studio兼容，在AndroidStudio里搜不到

### ISSUE THREAD

**Issue by tankcong** [pqpo/MvpGenerator#1]
Android Studio的plugin repo里搜不到插件，版本信息：
Android Studio 2.3
Build #AI-162.3764568, built on February 24, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by pqpo** [comment]
这个需要自己打成jar包本地安装的，没提供jar包，如有需要的话我上传个jar

**Comment by tankcong** [comment]
ok，我自己搞定吧，建议你也传一份上来，out of box嘛
